sudo: required
services:
  - docker

before_install:
  - docker build -t aniruddhchouksey/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true aniruddhchouksey/react-test npm run test

after_sucess:
  - docker build -t aniruddhchouksey/multi-client ./client
  - docker build -t aniruddhchouksey/multi-server ./server
  - docker build -t aniruddhchouksey/multi-worker ./worker
  - docker build -t aniruddhchouksey/multi-nginx ./nginx
  # log in to the docker cli
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push aniruddhchouksey/multi-client
  - docker push aniruddhchouksey/multi-server
  - docker push aniruddhchouksey/multi-worker
  - docker push aniruddhchouksey/multi-nginx
